Fix FILE_ATTRIBUTE_NORMAL AttributeError
Instead of using stat.FILE_ATTRIBUTE_NORMAL I used os.stat.FILE_ATTRIBUTE_NORMAL

AttributeError: 'builtin_function_or_method' object has no attribute 'FILE_ATTRIBUTE_NORMAL'